WAD2_12B_Group_Project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

rankedify/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rankedifyapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.default_page, name='default_page'),
    path('rankedify/', include('rankedifyapp.urls')),
    path('admin/', admin.site.urls),
    path('callback/', views.profile, name='callback'),
    path('new_friend/', views.add_friend, name='add_friend'),
    path('remove_friend/', views.remove_friend, name='remove_friend'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rankedifyapp/urls.py
from django.shortcuts import redirect
from django.urls import path
from rankedifyapp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'rankedifyapp'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('friends/', views.friends, name='friends'),
    path('error-page/', views.error_page, name="error-page"),
    path('callback/', views.get_spotify_data, name="callback"),
    path('api/receive_tracks/', views.receive_tracks, name='receive_tracks'),
    path('api/receive_minutes/', views.receive_minutes, name='receive_minutes'),
    path('api/receive_profile/', views.receive_profile, name='receive_profile'),
    path('api/receive_photo/', views.receive_photo, name='receive_photo'),
    path('api/receive_spotify_username/', views.receive_spotify_username, name='receive_spotify_username'),
    path('users/<slug:username_slug>', views.view_profile, name='view_profile'),
    path('new_friend/', views.add_friend, name='add_friend'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spotify_test/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path
from django.urls import include
from rankedify import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rankedify/', include('rankedify.urls')),
    path('callback/', views.index, name='index'),
    path('admin/', admin.site.urls),
]

rankedify/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_minutes_listened = models.IntegerField(default=0)  # Stores listening time
    favourite_album = models.CharField(max_length=255, blank=True, null=True)
    favourite_artist = models.CharField(max_length=255, blank=True, null=True)
    favourite_song = models.CharField(max_length=255, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', default='default.jpg', blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.total_minutes_listened} minutes"

rankedify/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["favourite_album", "favourite_artist", "favourite_song", "profile_picture"]

rankedify/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import ProfileForm
from .models import Profile


def index(request):
    leaderboard = Profile.objects.order_by("-total_minutes_listened")[:12] 
    return render(request, "rankedify/index.html", {"leaderboard": leaderboard})
@csrf_exempt
def receive_tracks(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            #print("Received Top Tracks:", data)
            return JsonResponse({"message": "Data received successfully"}, status=200)
        except json.JSONDecodeError:
            return JsonResponse({"error": "Invalid JSON"}, status=400)
    return JsonResponse({"error": "Invalid request"}, status=405)

@csrf_exempt
def receive_minutes(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            #print("Received Top Tracks:", data)
            return JsonResponse({"message": "Data received successfully"}, status=200)
        except json.JSONDecodeError:
            return JsonResponse({"error": "Invalid JSON"}, status=400)
    return JsonResponse({"error": "Invalid request"}, status=405)

def edit_profile(request):
    profile = request.user.profile
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("rankedfiy/users/username")
    else:
        form = ProfileForm(instance=profile)

    return render(request, "rankedify/edit_profile.html", {"form": form})




def user_register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        
        if password != confirm_password:
            messages.error(request, "Passwords do not match")
            return render(request, "rankedify/register.html")
        
        if User.objects.filter(username=username).exists():
            messages.error(request, "Username already taken")
            return render(request, "rankedify/register.html")
        
        user = User.objects.create_user(username=username, password=password)
        login(request, user)
        return redirect('rankedify:home')
    else:
        return render(request, "rankedify/register.html")

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        
        if user:
            login(request, user)
            return redirect('rankedify:home')
        else:
            return HttpResponse("Invalid login")
    
    return render(request, 'rankedify/login.html')

def user_logout(request):
    logout(request)
    return redirect('rankedify:home')

templates/rankedify/error-page.html
{% extends "rankedify/template-page.html" %}

{% block title %} Login-Error {% endblock %}

{% block main-body %}
    <div class="message-container">    
        <h2 >Login Error</h2>
        <p><b>Warning:</b> You must be logged in to view this page <a class="link" href="{% url 'rankedifyapp:home' %}"> Return Home</a> </p>
    </div>
{% endblock %}

templates/rankedify/friends.html
{% extends "rankedify/template-page.html" %}

{% load staticfiles %}

{% block title %} Friends {% endblock %}

{% block extra-js %}
<script src="{% static 'js/search_bar_scripts.js' %}" type="module"></script>
{% endblock %}

{% block main-body %}
<div class="friends-page-content">
    <section class="user-table">

        <div class="friends-list">
            <div class="friends-title">
                Friends
            </div>
        </div>

        <div class="user-entries">
            <ul class="user-entries">
                {% if friends|length > 0 %}
                    {% for friend in friends %}
                        <li class="friends-entry">
                            <span class="user-entry"><a href="{% url 'rankedifyapp:view_profile' friend.slug %}">{{ friend.username }}</a></span>
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
        </div>
    </section>


    <section class="user-table mt-12s">
        Find User <br>
        <input type="text" placeholder="Search..." id="user-search" class="leaderboard-search-box" />

    <div class="user-entries">
        <ul id="user-entries">
            {% if all_users|length > 0 %}
                {% for user in all_users %}
                    <li class="friends-entry">
                        <span class="user-entry"><a href="{% url 'rankedifyapp:view_profile' user.slug %}">{{ user.username }}</a></span> 
                    </li>
                {% endfor %}
            {% else %}
            <li class="friends-entry">
                <span class="user-entry">no current users</span> 
            </li>  
            {% endif %}
        </ul>
    </div>
    </section>
</div>
{% endblock %}

templates/rankedify/home.html
{% extends "rankedify/template-page.html" %}

{% load staticfiles %}

{% block title %} Home {% endblock %}

{% block extra-js %} 
<script src="{% static 'js/search_bar_scripts.js' %}" type="module"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
{% endblock %}

{% block main-body %}
<div class="page-splitter">
    <section class="leaderboard-container">
        
        <div class="leaderboard-search">
            User Search <input placeholder="search..." type="text" class="leaderboard-search-box" />
        </div>
        <div class="leaderboard">
            <div class="leaderboard-entry leaderboard-entry-title">
                <span class="leaderboard-position">Place</span> 
                <span class="leaderboard-username">Username</span> 
                <span class="leaderboard-listening-time">Listening Time (minutes)</span>
            </div>
            <ul class="non-user-entries"> 
                {% for profile in all_user_profiles %}
                    {% with forloop.counter  as i %}
                        <li class="leaderboard-entry">
                            <span class="leaderboard-position">#{{ i }}</span> 
                            <span class="leaderboard-username"> {{ profile.username }}</span> 
                            <span class="leaderboard-listening-time"> {{ profile.listening_minutes }} </span>
                        </li>
                    {% endwith %}
                {% endfor %}      
            </ul>

            {% if current_user_profile is not None %}
              {% for profile in all_user_profiles %}
                {% if profile == current_user_profile %}
                  {% with forloop.counter as user_position %}
                      <div class="leaderboard-user-entry">
                        <span class="leaderboard-position text-center"> 
                            <span class="text-center">You</span> <br> #{{ user_position }}
                        </span>
                        <span class="leaderboard-username"> {{ current_user_profile.username }} </span> 
                    <span class="leaderboard-listening-time"> {{ current_user_profile.listening_minutes }} </span>
                </div>
            {% endwith %}
        {% endif %}
    {% endfor %}
{% endif %}
        </div>

        
    </section>

    <div class="page-seperator-line">
    </div>

    <canvas id="average_listening_time" class="graph">

    </canvas>
</div>

<script>
    const xValues = [50,60,70,80,90,100,110,120,130,140,150];
    const yValues = [7,8,8,9,9,9,10,11,14,14,15];
    
    new Chart("average_listening_time", {
      type: "line",
      data: {
        labels: xValues,
        datasets: [{
          fill: false,
          lineTension: 0,
          backgroundColor: "#1DB954",  // Spotify Green
          borderColor: "rgba(30, 215, 96, 0.8)", // Slightly transparent green border
          pointBackgroundColor: "#1DB954",
          pointBorderColor: "#fff",
          pointHoverBackgroundColor: "#fff",
          pointHoverBorderColor: "#1DB954",
          data: yValues
        }]
      },
      options: {
        legend: { display: false },
        scales: {
          yAxes: [{
            ticks: { min: 0},
            scaleLabel: {
              display: true,
              labelString: "listening time (minutes)"
            }
          }]
        }
      }
    });
    </script>
{% endblock %}

templates/rankedify/index.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <title>My Spotify Profile</title>
    <script src="{% static 'scripts/script.js' %}" type="module"></script>
</head>

<body>
    <h1>Display your Spotify profile data</h1>

    <section id="profile">
        <h2>Logged in as <span id="displayName"></span></h2>
        <span id="avatar"></span>
        <ul>
            <li>User ID: <span id="id"></span></li>
            <li>Email: <span id="email"></span></li>
            <li>Spotify URI: <a id="uri" href="#"></a></li>
            <li>Link: <a id="url" href="#"></a></li>
            <li>Profile Image: <span id="imgUrl"></span></li>
        </ul>
    </section>

    <section id="top_songs">
        <h2>Your Top Tracks</h2>
        <span id="track-list"></span>
    </section>

    <section>
        <h2>Your Listening Minutes:</h2>
        <strong><span id="listeningMinutes"></span></strong>
    </section>
</body>
</html>

templates/rankedify/login.html
{% extends "rankedify/template-page.html" %}

{% block title %} Log-in {% endblock %}

{% block main-body %}
    <div class="login-and-create-account-form">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form method="post" action="{% url 'rankedifyapp:login' %}">
            {% csrf_token %}
            <div class="user-login">
                <div class="input-container">
                    <span class="input-title">
                        <label for="username">Username:</label>
                    </span>
                    <input class="text-field" id="username" name="username">
                </div>
                <div class="input-container">
                    <span class="input-title">
                        <label for="password">Password:</label>
                    </span>
                    <input class="text-field" id="password" name="password" type="password">
                </div>
            </div>
            <input class="button" type="submit" value="Log-in"/>
        </form>
        <a href="/rankedify/signup" class="link">Don't have account?</a>
    </div>
{% endblock %}

templates/rankedify/profile.html
{% extends "rankedify/template-page.html" %}

{% load staticfiles %}

{% block extra-js %} 
<script src="{% static 'js/spotify_script.js' %}" type="module"></script>

<script src={% static 'js/profile_scripts.js' %}></script>
    
{%endblock%}

{% block title %}
    Profile
{% endblock %}

{% block main-body %}
    <div class="page-splitter">
        <div class="profile-content pl-[5%] w-[60%]">
            <div class="picture-and-friend flex gap-x-2">
                <span id="avatar"></span>
            </div>

            <div class="mt-12">
                <div class="profile-info-container">
                    <span class="field-title"><strong>Username:</strong></span>
                    <input class="text-field" value="{{ username }}" readonly>
                </div>
                <div class="profile-info-container">
                    <span class="field-title"><strong>Spotify Username:</strong>
                        <span id="displayname"></span>
                    </span>
                    <input class="text-field" value="{{ spotify_username }}" readonly>
                </div>
                <div class="profile-info-container">
                    <span class="field-title"><strong>Favourite Song:</strong></span>
                    <input class="text-field" id="favourite-song" value="{{ top_song }}" readonly>
                </div>
                <button class="edit-button button">Edit Favourite Song</button>
                <section id="top_songs">
                    <div class="profile-info-container">
                    <span class="field-title"><strong>Top Songs Right Now:</strong></span>
                    </div>
                    <span id="track-list"></span>
                </section>
            </div>
        </div>

        <div class="page-seperator-line">
        </div>

        <canvas class="max-w-[450px] mx-auto" height="188" width="450"></canvas>
    </div>
{% endblock %}

templates/rankedify/signup.html
{% extends "rankedify/template-page.html" %}

{% block title %} Sign Up {% endblock %}

{% block main-body %}
    <div class="login-and-create-account-form">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form method="post" action="{% url 'rankedifyapp:signup' %}">
            {% csrf_token %}
            <div class="user-login">
                <div class="input-container">
                    <span class="input-title">
                        <label for="username">Username:</label>
                    </span>
                    <input class="text-field" id="username" name="username">
                </div>
                <div class="input-container">
                    <span class="input-title">
                        <label for="forename">Forename:</label>
                    </span>
                    <input class="text-field" id="forename" name="forename">
                </div>
                <div class="input-container">
                    <span class="input-title">
                        <label for="surname">Surname:</label>
                    </span>
                    <input class="text-field" id="surname" name="surname">
                </div>
                <div class="input-container">
                    <span class="input-title">
                        <label for="email">Email:</label>
                    </span>
                    <input class="text-field" id="email" name="email">
                </div>
                <div class="input-container">
                    <span class="input-title">
                        <label for="password">Password:</label>
                    </span>
                    <input class="text-field" id="password" name="password" type="password">
                </div>
                <div class="input-container">
                    <span class="input-title">
                        <label for="confirm_password">Confirm Password:</label>
                    </span>
                    <input class="text-field" id="confirm_password" name="confirm_password" type="password">
                </div>
            </div>
            <input class="button" type="submit" value="Create Account"/>
        </form>
        <a href="/rankedify/login" class="link">Already have an account?</a>
    </div>
{% endblock %}

templates/rankedify/template-page.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
    <head>
        <!--Include tailwind css-->
        <script src="https://cdn.tailwindcss.com"></script>
        
        <!--Include JQuery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

        <!--Links jquery script that applies styling to the appropiate elements-->
        <script src="{% static 'js/page_styling.js' %}"></script>

        {% block extra-js %} {% endblock %}

        <title>Rankedify - {% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav>
            <div id="logo">Rankedify</div>
            <a href="/rankedify/home"><div class="nav-item">Home</div></a>
            {% if user.is_authenticated %}
                <a href="/rankedify/friends"><div class="nav-item">Friends</div></a>
            {% endif %}

            {% if not user.is_authenticated %}
                <a href="/rankedify/login"><div class="nav-item">Login</div></a>
            {% else %}
                <a href="/rankedify/logout"><div class="nav-item">Logout</div></a>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="/rankedify/profile"><div class="nav-item">Profile</div></a>
            {% endif %}
        </nav>

        <div id="page-body">
            {% block main-body %}
            {% endblock %}
        </div>
    </body>
</html>
</body>
</html>

templates/rankedify/userprofile.html
{% extends "rankedify/template-page.html" %}

{% load staticfiles %}

{% block extra-js %}

<script src={% static 'js/profile_scripts.js' %}></script>

<script>
    let username_var = "{{ username }}";
    let is_friend = "{{ is_friend }}"
</script>

<script src="{% static 'js/add_friend.js' %}"></script>

{%endblock%}

{% block title %}
    Profile
{% endblock %}

{% block main-body %}
    <div class="page-splitter">
        <div class="profile-content pl-[5%] w-[60%]">
            <div class="picture-and-friend flex gap-x-2">
                <img src="{{ MEDIA_URL }}{{ photo }}"
                     alt="User Avatar" />
                <button id="friend-button" onclick="toggleFriendButtonStatus(this)" class="h-10 bg-zinc-950 text-white semi-bold p-2 w-32">
                    {% if is_friend %}
                        Unfriend
                    {% else %}
                        Add Friend
                    {% endif %}
                </button>
            </div>

            <div class="mt-12">
                <div class="profile-info-container">
                    <span class="field-title">Username:</span>
                    <input class="text-field" value="{{ username }}" readonly>
                </div>
                <div class="profile-info-container">
                    <span class="field-title">Spotify Username:
                        <span id="displayname"></span>
                    </span>
                    <input class="text-field" value="{{ spotify_username }}" readonly>
                </div>
                <div class="profile-info-container">
                    <span class="field-title">Favourite Song:</span>
                    <input class="text-field" id="favourite-song" value="{{ favourite_song }}" readonly>
                </div>
            </div>
        </div>

        <div class="page-seperator-line">
        </div>

        <canvas class="max-w-[450px] mx-auto" height="188" width="450"></canvas>
    </div>
{% endblock %}